version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_SHARED_BUFFERS: "110MB"  #Memória/espaço em buffer compartilhada em entre as conexões
      POSTGRES_WORK_MEM: "20MB"     # Memória utilizada para manipular dados em buffer
    ports:
      - "2000:5432"
    volumes:
      # - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "145MB"

  api01: &api
    image: marcioluzjr/rinha_api:v12
    restart: unless-stopped
    hostname: api01
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_started 
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "160MB"

  api02:
    <<: *api 
    hostname: api02 
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_started 

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api01:
        condition: service_started
      api02:
        condition: service_started 
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.37"
          memory: "85MB"

networks:
  default:
    driver: bridge

volumes:
  db-data: