version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "2000:5432"
    volumes:
      # - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

  api01: &api
    image: marcioluzjr/rinha_api:v1
    hostname: api01 
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api 
    hostname: api02 
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

networks:
  default:
    driver: bridge

volumes:
  db-data: