version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "2000:5432"
    volumes:
      # - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"