version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    networks:
      default:
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
      #- ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.config_file
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "145MB"

  api01: &api
    container_name: api01
    image: marcioluzjr/rinha_api:v13
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
    networks:
      default: 
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "160MB"

  api02:
    <<: *api
    container_name: api02
    networks:
      default: 

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api01:
        condition: service_started
      api02:
        condition: service_started
    ports:
      - "9999:9999"
    networks:
      default: 
    deploy:
      resources:
        limits:
          cpus: "0.37"
          memory: "85MB"

  # tester:
  #   image: debian:latest
  #   command: ["/bin/bash", "-c", "apt-get update && apt-get install -y wget && apt-get install -y iputils-ping && apt-get install -y curl && apt-get install -y nmap && apt-get clean && exec bash"]
  #   networks:
  #     default: 
  #   stdin_open: true
  #   tty: true
  #   restart: unless-stopped

networks:
  default:
    driver: bridge
